//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::{entity::prelude::*, ActiveValue};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "series")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
    pub mal_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::series_sources::Entity")]
    SeriesSources,
}

impl Related<super::series_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeriesSources.def()
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        let mut this = self;
        let now = chrono::Utc::now().to_rfc3339();
        if insert {
            this.created_at = ActiveValue::Set(Some(now.clone()));
        } else {
            this.created_at = ActiveValue::NotSet;
        }
        this.updated_at = ActiveValue::Set(Some(now));
        Ok(this)
    }
}
